#ifndef OBJECT_TYPES
#define OBJECT_TYPES

#include "shared.h"

class ObjectTypes
{
public:
	ObjectTypes();
	class Object * CreateFromType(Uint8 type);
	unsigned int SerializedSize(Uint8 type);
	enum {OVERLAY, INTERFACE, BUTTON, TOGGLE, SELECTBOX, SCROLLBAR, TEXTBOX, TEXTINPUT, STATE,
		TEAM, PLAYER, CIVILIAN, GUARD, ROBOT, TERMINAL, VENT, HEALMACHINE,
		CREDITMACHINE, SECRETRETURN, SURVEILLANCEMONITOR, TECHSTATION, INVENTORYSTATION, TEAMBILLBOARD,
		PLUME, SHRAPNEL, BODYPART, BLASTERPROJECTILE, LASERPROJECTILE, ROCKETPROJECTILE, FLAMERPROJECTILE,
		PLASMAPROJECTILE, FLAREPROJECTILE, WALLPROJECTILE, BASEDOOR, PICKUP, WARPER, DETONATOR,
		FIXEDCANNON, GRENADE, WALLDEFENSE};

private:
	unsigned int serializedsize[0xFF];
};

#endif